### PR TITLE
Support changing the window focus mode

### PR DESCRIPTION
**Pull request by huettner94**
Users might want to update their preferences regarding the focus-mode of the window manager.
This can allow a user to configure the focus-mode in:
- "click": where you need to click on a window to get it in focus (current setting)
- "sloppy" where the window below your cursor is always in focus automatically.

I'm quite unsure of the placement of this setting. But i thought this is the most fitting location.

I would be happy to accept feedback regarding this change

### CODE REVIEW

**Comment by cassidyjames** [comment]
For context, what is the reason behind adding this setting?

**Comment by huettner94** [comment]
Hi cassidyjames,
I find the "sloppy" setting extremely useful when working with keyboard shortcuts in multiple windows. It allows me to move my mouse just over the window I want to use without the need to click somewhere.

I came to use it when working with programs where clicks can cause undesired effects, such as:
- when you click in an image editing program and you draw some kind of color somewhere not intended
- when you use a code editor and a click causes your cursor to jump to a different position.

I thought about adding it as a user-visible setting because I know a few people who like this feature after they get to know it. But if the feature is hidden  in a "non-ui" setting its not very discover-able for the user.

Regards

**Comment by jeremypw** [comment]
@huettner94 converting to draft as there are conflicts and no recent activity.  However, I would quite like to see this merged - it seems Gala does support these settings as manually altering them does change window behaviour.

@elementary/ux Is this something you would be willing to consider?

**Comment by huettner94** [comment]
Hi jeremypw,

i have moved away from Elementary so unfortunately i cant test any change anymore.
I would close this PR then but feel free to use the diff if you want to integrate it.

**Comment by jeremypw** [comment]
@huettner94 OK, thanks for letting us know.  I'll wait for UX team opinion on whether they would accept these extra settings and if so may adopt the code.  Thanks for the contribution!

**Pull request closed without merging**
