### PR TITLE
Scroll to selected wallpaper after loading

### LINKED ISSUE #53: scroll to the currently selected background
it would be a nice touch

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43962957-scroll-to-the-currently-selected-background?utm_campaign=plugin&utm_content=tracker%2F57462545&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57462545&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by davidmhewitt**
Fixes #53

### CODE REVIEW

**Comment by davidmhewitt** [comment]
This should now be ready to review again. I think it was previously working intermittently due to a bit of a hack in the way the wallpapers are inserted into the FlowBox. This hack has now been removed in a previous commit, so ready for re-test.

**Comment by matzipan** [comment]
It's not doing the trick for me. It still doesn't work scroll to the wallpaper and now I can't seem to be able to set the wallpaper neither using master nither using this branch.

**Comment by matzipan** [comment]
I did not see any error messages printed if running from console.

**Comment by davidmhewitt** [comment]
@matzipan I think this is good for retesting now

**Pull request merged**
