### PR TITLE
Sort wallpapers

### LINKED ISSUE #109: Add a sort function to wallpapers
There doesn't seem to be any sort function set so wallpapers just load in at whatever order they load in

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/57262226-add-a-sort-function-to-wallpapers?utm_campaign=plugin&utm_content=tracker%2F57462545&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57462545&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lenemter**
Closes #109 

User wallpapers first, then system wallpapers, then solid color. Wallpapers sorted by creation date from recent to oldest

### CODE REVIEW

**Comment by jeremypw** [comment]
@danrabbit What is the best sort order for this?  I think maybe user added wallpapers should appear *first* as presumably they are the ones the user is most interested in (and will be visible after adding without expanding the window and will be most easily removed)?

**Comment by danrabbit** [comment]
Yeah I think I agree with @jeremypw that user walls first makes sense

**Review by jeremypw — CHANGES_REQUESTED** [review]
Need to invalidate the sort order when a wallpaper is added (or removed).  Otherwise an added user wallpaper does not appear at the start (until app restarted)

**Comment by lenemter** [comment]
Now recently added wallpapers are sorted first

**Comment by lenemter** [comment]
Seems like `get_creation_date_time` is unavailable in OS 6

**Review by jeremypw — APPROVED** [review]

**Comment by jeremypw** [comment]
Yes, makes sense to use Unix time for sorting.

**Pull request merged**
