### PR TITLE
Port to GTK4

### PR DESCRIPTION
**Pull request by treppenwitz03**
Blocked by:
- [x] Depends on libplank which uses GTK3, and may not be used in the future since https://github.com/elementary/dock/tree/main
- [x] Depends on libgnome-desktop which is still in GTK3
- [x] FIX DND
- [x] Freezes when opened again
- [ ] Find a way to get primary monitor
- [x] Handle https://github.com/elementary/switchboard-plug-pantheon-shell/blob/master/src/Views/Appearance.vala#L224-L241

PRs to look out for:
- [x] https://github.com/elementary/switchboard-plug-pantheon-shell/pull/310
- [ ] https://github.com/elementary/switchboard-plug-pantheon-shell/pull/299
- [ ] https://github.com/elementary/switchboard-plug-pantheon-shell/pull/295

### CODE REVIEW

**Comment by danrabbit** [comment]
It looks like gnome-desktop is mainly used here to get display names? I'm not sure if there's a way to get those directly from Gdk.Display, but it looks like we're getting them from Mutter in the displays plug.

It looks like Plank keeps its settings in Gsettings at `/net/launchpad/plank/docks/dock1/`, so you can probably ditch libplank here and use `Glib.Settings` directly

**Comment by ZenitsuDev** [comment]
It hangs when reopened, and the problem seems to originate in the wallpaper page

**Comment by ZenitsuDev** [comment]
> It hangs when reopened, and the problem seems to originate in the wallpaper page

this is fixed now

**Comment by jeremypw** [comment]
@danrabbit This will need the Gtk.RadioButton replacing now.

**Comment by lenemter** [comment]
@danrabbit styling of CheckButton has changed in GTK4 and css style from master doesn't work. I couldn't fix it

**Pull request closed without merging**
