### PR TITLE
Multitasking: redesign

### PR DESCRIPTION
**Pull request by danrabbit**
* Keep neat illustrations while adding explicit labels for each combobox
* Solves a problem in https://github.com/elementary/switchboard-plug-pantheon-shell/pull/299 where this view forces the width of the window to increase
* Add a scrollbox so we don't force the height of the window either

### CODE REVIEW

**Comment by jeremypw** [comment]
Screenshot from 2022-06-30 19 10 51

**Comment by jeremypw** [comment]
My initial reaction is that the comboboxes are a *lot* wider than the text therein, which looks a bit odd.

**Comment by jeremypw** [comment]
Should #299 be merged first - I guess this layout works better with that design?

**Review by jeremypw — COMMENTED** [review]
Code looks good.Just left a comment about appearance.

Also it looks like the settings and gala has the ability to have different custom commands assigned to different corners.  As you can choose "custom command" for more than one corner it would make sense to have separate entries for each command command rather than an obscure way of entering multiple commands into one entry.  This layout would facilitate that.

**Comment by danrabbit** [comment]
You're right! I didn't realize that was possible. I'll update this branch to take advantage of that. From gsettings:

> If you just put a single command, it will be used for every hot corner assigned to 'custom-command'. If you instead use the pattern 'hotcorner-topleft:command;;hotcorner-bottomright:command' the specific commands will be used per hotcorner. Possible identifiers are 'hotcorner-[topleft; topright; bottomleft; bottomright]' followed by a ':' and then the command. ';;' is used as delimiter between command definitions.

**Comment by danrabbit** [comment]
@jeremypw okay you should be able to set per-corner custom commands now!

Screenshot from 2022-06-30 16 28 56

**Comment by jeremypw** [comment]
Yeah, I did not know until I saw the description of the setting - not exactly discoverable!

**Review by jeremypw — CHANGES_REQUESTED** [review]
Looks good now.  Just a couple of bits of residual debugging code  (lines 94, 210).

It might be better to use a variant array to store the custom commands, like Files tab info does, rather than manipulating strings but that can be considered later.

**Comment by danrabbit** [comment]
Yeah I think ideally this should probably be a string array in Gala's gsettings. It's pretty ugly like you said doing this string manipulation

**Review by jeremypw — APPROVED** [review]

**Pull request merged**
