### PR TITLE
Appearance settings for accent color

### PR DESCRIPTION
**Pull request by cassidyjames**
UI for https://github.com/elementary/stylesheet/issues/375.

- ~Adds a new Appearance tab to Desktop settings~
- Adds a new Accent Color setting

screenshot from 2018-12-06 14 32 26 2x

# Todo:

- [ ] Add slate variant in https://github.com/elementary/stylesheet/issues/375
- [x] Make color buttons exclusive
- [x] Hook color buttons up to switch the theme
- [x] Consider graduating a11y settings since this pane is so barren

### CODE REVIEW

**Comment by danrabbit** [comment]
Might consider using radiobuttons and copying the CSS from [calendar](https://github.com/elementary/calendar/blob/master/data/style/ColorButton.css)

**Comment by cassidyjames** [comment]
@danrabbit ah yeah now that we've done that I think that could work. The alternative is something more visual like #137. But I think the radios are more flexible and probably clear enough, especially since the accents update instantly.

**Comment by cassidyjames** [comment]
@danrabbit updated

**Comment by cassidyjames** [comment]
Update:

image
image

**Comment by cassidyjames** [comment]
Or dropping "Default" from the label: 

image

**Comment by cassidyjames** [comment]
Updated screenshots. Using greenfield on Hera, so ignore the text in switches.

image

image

Looks like I'm not setting the right active state on load, so I'll need to fix that. Otherwise, this is real close.

**Comment by cassidyjames** [comment]
@danrabbit the latest commit makes the code structure a little messier, cleanup suggestions welcome. Originally I was only going to attach the accent UI if the stylesheet had the right prefix, but it was selecting one of the radios when they were constructed, and then because that changed the stylesheet, it was attaching. :stuck_out_tongue: An alternative might be an "unsupported" radio that we don't attach, like in dock settings, but I couldn't get that to work as cleanly as I'd like.

**Comment by cassidyjames** [comment]
(an advantage of the current approach: technically there's nothing preventing this from shipping in Hera since it'll be hidden)

**Pull request merged**
