### PR TITLE
Undo mechanism for trashing wallpapers

### LINKED ISSUE #111: Add an undo mechanism for trashing wallpapers
Preferably using the toast undo pattern

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/57281970-add-an-undo-mechanism-for-trashing-wallpapers?utm_campaign=plugin&utm_content=tracker%2F57462545&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57462545&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lenemter**
Closes #111 
Also, now removed wallpapers are not completely deleted, but trashed instead

### CODE REVIEW

**Comment by jeremypw** [comment]
The removed wallpaper does not seem to reappear when I press the "Undo" button on the toast. Also when this is merged you should really push a corresponding commit to the `gtk4` branch,

**Comment by jeremypw** [comment]
Looks like `wallpaper_for_removal` is being destroyed before it can be added back.

**Review by jeremypw — APPROVED** [review]
This now works as expected and follows the pattern suggested by the OP.  Thanks!

**Comment by jeremypw** [comment]
@lenemter Are you able to work on the `gtk4` branch? You will need to install the Gtk4 version of Switchboard (renamed to `io.elementary.settings`) as well but you can have both the master (Gtk3) version and the Gtk4 version installed at the same time - they do not interfere with each other.  The changes made in this PR will need some amendment to compile with Gtk4.

**Comment by lenemter** [comment]
OS 6 doesn't support GTK 4, right? So I need to install OS 7 first. I'll push into `gtk4` branch as soon as I can, can't start working now, it's 02:40 for me ;)

**Comment by jeremypw** [comment]
Oh, yes - I am working with OS7.  Good night!

**Pull request merged**
