### PR TITLE
Make color buttons order consistent system-wide

### PR DESCRIPTION
**Pull request by fabiozaramella**
Sorry for being nitpicking, but this makes the color order consistent with Calendar, Files and Tasks.

### CODE REVIEW

**Comment by cassidyjames** [comment]
So the reason I left Blueberry first here is because it's the default; it felt more natural to have it at the beginning of the row.

**Comment by fabiozaramella** [comment]
I imagined that was the reason but I think it would be better to keep them consistent. Also, blueberry looks out of place at the beginning just before strawberry.

**Comment by danrabbit** [comment]
I'm personally in favor of having them in order. I'm not sure there's a huge benefit to having the default blue be first

**Comment by cassidyjames** [comment]
Another option (similar to what GNOME does) is to just cycle the rainbow around so Blue is at the beginning. So you end up with this:

Screenshot from 2020-10-13 13 45 42@2x

Screenshot from 2020-10-13 13 45 34@2x

**Comment by fabiozaramella** [comment]
> Another option (similar to what GNOME does when showing their color palette in docs) is to just cycle the rainbow around so Blue is at the beginning. So you end up with this:
> 
> Screenshot from 2020-10-13 13 45 42@2x
> 
> Screenshot from 2020-10-13 13 45 34@2x

Well, that looks even better! 😍 It'll need to be reflected in Files and Calendar too though, but it's absolutely a +1 from me.

**Comment by cassidyjames** [comment]
Another option is to rotate it around blue, but switch the order. This feels more natural to me for some reason.

Screenshot from 2020-10-13 14 10 08@2x

**Pull request closed without merging**
