### PR TITLE
Refactor Wallpaper.vala

### PR DESCRIPTION
**Pull request by donadigo**
This branch refactors Wallpaper.vala and makes some changes to how the UI and code works:

* The solid color is no longer displayed as a wallpaper in the wallpaper view, instead it has a new "Solid Color" entry in the wallpaper method combobox
* The combobox is never insensitive now, it changes it's value according to the type of wallpaper you've set
* Fix solid color not being applied at all because of wrong value assigned to the primary-color key
* Removes unneded code
* Move utility code to Utils.vala
* Reworks how wallpapers are loaded
* Improves readability of the code and removes hacks

I'm still not satisfied with the result, but it's a start. The next thing I would to make is an abstract WallpaperProvider class which would provide wallpapers and useful functions to make the plug more extensible.

### CODE REVIEW

**Comment by codygarver** [comment]
This does not compile for me.

**Comment by donadigo** [comment]
@codygarver it does for me. Can you paste the output of the build? I'm currently using valac 0.34.7.

**Comment by Philip-Scott** [comment]
@donadigo I think you might have forgotten to commit some changes, your branch should be fixed now though :)

**Comment by codygarver** [comment]
Closing since this stuff was ported to Tumbler recently.

**Pull request closed without merging**
